default:
  tags:
  - webserver

stages:
  - deploy

deploy-job:
  stage: deploy
  environment:
    name: production
  script:
    - sudo rm -fr /app/quiz
    - sudo mkdir /app/quiz
    - tar cf - . | sudo tar -C /app/quiz --exclude='./.git' --exclude='./.gitlab-ci.yml' -xvf -
  when: manual
